package com.hoau.hoaureport.module.configreport.server.dao;

import java.util.List;

import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import com.hoau.hoaureport.module.configreport.shared.domain.MonthSqlEntity;

@Repository
public interface MonthSqlEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    int insert(MonthSqlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    int insertSelective(MonthSqlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    MonthSqlEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    int updateByPrimaryKeySelective(MonthSqlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    int updateByPrimaryKeyWithBLOBs(MonthSqlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-12 17:19:57
     */
    int updateByPrimaryKey(MonthSqlEntity record);
    /**
     * 整月报表sql数据查询
     * @param monthsql
     * @return
     */
	List<MonthSqlEntity> selectListBysqlType(MonthSqlEntity monthsql);
	/**
	 * 总记录数
	 * @param sqlEntity
	 * @return
	 */
	Long queryTotalCount(MonthSqlEntity sqlEntity);
	/**
	 * 分页查询
	 * @param sqlEntity
	 * @param row
	 * @return
	 */
	List<MonthSqlEntity> queryMonthSql(MonthSqlEntity sqlEntity, RowBounds row);

}