package com.hoau.hoaureport.module.configreport.server.dao;

import com.hoau.hoaureport.module.configreport.shared.domain.ReportOmsTargetEntity;
import java.math.BigDecimal;

public interface ReportOmsTargetEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_OMS_TARGET
     *
     * @mbggenerated Fri Sep 29 15:09:27 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_OMS_TARGET
     *
     * @mbggenerated Fri Sep 29 15:09:27 CST 2017
     */
    int insert(ReportOmsTargetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_OMS_TARGET
     *
     * @mbggenerated Fri Sep 29 15:09:27 CST 2017
     */
    int insertSelective(ReportOmsTargetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_OMS_TARGET
     *
     * @mbggenerated Fri Sep 29 15:09:27 CST 2017
     */
    ReportOmsTargetEntity selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_OMS_TARGET
     *
     * @mbggenerated Fri Sep 29 15:09:27 CST 2017
     */
    int updateByPrimaryKeySelective(ReportOmsTargetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_OMS_TARGET
     *
     * @mbggenerated Fri Sep 29 15:09:27 CST 2017
     */
    int updateByPrimaryKey(ReportOmsTargetEntity record);
}