package com.hoau.hoaureport.module.configreport.server.dao;

import java.util.List;

import com.hoau.hoaureport.module.configreport.shared.domain.WayBillZipEntity;

import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
/**
 * 运单物流时间报表导出数据管理Dao
 * @author 273503
 *
 */
@Repository
public interface WayBillZipEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-11 18:49:46
     */
    int insert(WayBillZipEntity record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author 273503
     * @date 2016-07-11 18:49:46
     */
    int insertSelective(WayBillZipEntity record);
    /**
     * 分页查询
     * @param zipEntity
     * @param row
     * @return
     */
	List<WayBillZipEntity> queryByEntity(WayBillZipEntity zipEntity,
			RowBounds row);
	/**
	 * 总记录数
	 * @param zipEntity
	 * @return
	 */
	Long queryCount(WayBillZipEntity zipEntity);
	/**
	 * 根据ID查询
	 * @param zipEntity
	 * @return
	 */
	WayBillZipEntity queryById(WayBillZipEntity zipEntity);
	/**
	 * 根据编码查询
	 * @param zipNum
	 * @return
	 */
	WayBillZipEntity queryByZipNum(String zipNum);
	/**
	 * 更新
	 * @param zipEntity
	 */
	long update(WayBillZipEntity zipEntity);
	/**
	 * 根据创建时间删除数据
	 * @param date
	 * @return
	 */
	int deleteByCreatedate(String datename);
}